- name: Provision a EC2
  hosts: localhost
  gather_facts: False

  vars:
    region: us-east-1       # Region may affect response and pricing
    image: ami-08a0d1e16fc3f61ea # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    instance_type: t2.micro       # Choose instance type, check AWS for pricing

  tasks:
    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "basic-ec2-ins"
        instance_type: "{{ instance_type }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
        tags:
          Environment: Testing

    - name: Facts
      block: # This block prints out instance data

      - name: Get instances facts
        amazon.aws.ec2_instance_info:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          region: "{{ region }}"
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"