---
# Include variables about our environment
- hosts: localhost
  connection: local
  pre_tasks:
    # Include variables about our environment
    - name: Include the variables specific to the environment
      include_vars: envs/{{ environ }}
  tags: env
  vars:
    - ansible_ssh_user: default
  roles:
    - { role: provision-vpc, tags: ['vpc', 'subnet', 'sg', 'peer-links'] }
    - { role: provision-ec2-new, tags: ['ec2'] }





