---
- hosts: localhost
  connection: local
  tags: prepare_cloud
  vars:
    - ansible_ssh_user: default
  roles:
    - { role: hello_world, tags: ['dump_vars'] }
    - { role: prepare_cloud, tags: ['prepare_cloud'] }

# Include variables about our environment
- hosts: localhost
  connection: local
  pre_tasks:
    # Include variables about our environment
    - name: Include the variables specific to the environment
      include_vars: envs/{{ environ }}.yml
  tags: env
  vars:
    - ansible_ssh_user: default
  roles:
    - { role: hello_world, tags: ['dump_vars'] }
    - { role: provision-vpc, tags: ['vpc', 'subnet', 'sg', 'peer-links'] }
    - { role: provision-ec2, tags: ['ec2'] }



