---
- name: Gather all registered virtual machines
  local_action:
    module: vmware_vm_facts
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
