---
- name: Gather all registered virtual machines
  local_action:
    module: vmware_vm_facts
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
  register: all_vms

- name: List VMs to stdout
  debug: msg="{{ all_vms }}"
